### ISSUE TITLE
chars in last preview exists in the next

### ISSUE THREAD

**Issue by timsu92** [junegunn/fzf-git.sh#11]
## Version
- [fzf]: 0.33.0 installed using Git
- [fzf-git.sh]: commit e44dfb3
- [bat]: 0.21.0 installed using `bat_0.21.0_amd64.deb`
- OS: Ubuntu 22.04.1 LTS on WSL2
- Terminal: Windows Terminal

## Step to reproduce
1. `ctrl-G` `ctrl-F`
2. Move cursor onto a file which has words long enough in the preview window.
3. Move cursor onto another file whose preview produced by [bat] overlaps in terminal with the output of last file.

## expected behavior
Preview of the "another file" only

## actual behavior
- In the header and footer of bat's production, it shows the preview result of last file if the header is shorter in width. Plus, the char before "File" and "Size" is doing the same.
- In the content of the newly previewing file, there are two spaces in each line locates between the gridline differentiating line number and content and content. And the first space shows whatever it was in the last preview.
#### first file
![image](https://user-images.githubusercontent.com/33785401/187377751-60f2f176-9de5-4270-8575-c0878d0a9a25.png)
#### "another file"
![image](https://user-images.githubusercontent.com/33785401/187377808-758a0da9-ba42-46c6-af24-494ece1f5316.png)

[fzf]: https://github.com/junegunn/fzf
[fzf-git.sh]: https://github.com/junegunn/fzf-git.sh
[bat]: https://github.com/sharkdp/bat

**Comment by junegunn** [comment]
Is the problem still reproducible when you set

```sh
_fzf_git_cat="bat --style=numbers --color=always --pager=never"
```

I'm trying to see if it's caused by the way your terminal emulator displays box-drawing characters bat uses.

**Comment by timsu92** [comment]
No, this issue can be solved by both your shell var and `_fzf_git_cat="bat --style=numbers --color=always"`. But removing `--style=numbers` will cause the problem.

**Comment by timsu92** [comment]
BTW, `--color=always` is required or the line numbers will be gone

**Comment by junegunn** [comment]
So how does this render on your terminal? Are the ends of the horizontal lines aligned with `.md`, or are the lines shorter than they look on this page?
```sh
cat << EOF
───────┬────────────────
       │ File: README.md
───────┼────────────────
EOF
```

If they are shorter, it explains why some characters are not properly cleared on the preview window. fzf calculates the width of each character of a line and only clears the remaining line.

**Comment by timsu92** [comment]
It seems that they aren't shorter🤔

I copied them line-by-line at first and them copied them as a whole.
![image](https://user-images.githubusercontent.com/33785401/187869004-eb500a2a-262b-48bc-be82-78c43a62504d.png)

**Comment by timsu92** [comment]
@junegunn May I confirm whether spaces you sent me were actually spaces? I'm afraid if there's something different induced by the clipboard.

**Comment by junegunn** [comment]
Yes.

I was wondering why the horizontal lines in your screenshot are so short, taking only half the width of the preview window.

![image](https://user-images.githubusercontent.com/700826/188348191-4e118cc8-d013-43f9-8764-d4f411078d0f.png)

`fzf --preview 'bat --color=always {}'` looks like this on my machine.

![image](https://user-images.githubusercontent.com/700826/188348483-5fba3218-e938-4251-880f-a4c26977ded3.png)

**Comment by timsu92** [comment]
I'm not sure though. I get this by `fzf --preview 'bat --color=always {}'`:
![image](https://user-images.githubusercontent.com/33785401/188355705-a507d18f-3f27-4a06-bb6a-2815a01673bf.png)

I see you use a font other than mine in other issue. Would that be the cause?
I use [JetBrainsMono NerdFont](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/JetBrainsMono/Ligatures/Regular/complete/JetBrains%20Mono%20Regular%20Nerd%20Font%20Complete%20Windows%20Compatible.ttf). What's yours? Is there a link?

## Situation with other fonts

In Windows Terminal, there are several fonts preinstalled. Most of them show like mine, except for these which currupts a lot of borders:

### LiSu
![image](https://user-images.githubusercontent.com/33785401/188356794-d41320f0-17a4-4675-95e9-c9ffb8183d28.png)

### MS Gothic
![image](https://user-images.githubusercontent.com/33785401/188372199-258d522b-2985-4cfd-8251-20d32c9ef22b.png)

### NSimSun
![image](https://user-images.githubusercontent.com/33785401/188372415-59929a55-cc07-486e-8039-b5fd0f1a6b5e.png)

### YouYuan
This currupts a lot of borders.
![image](https://user-images.githubusercontent.com/33785401/188372526-b391cfcd-2be6-4940-9163-35cadfa5b146.png)

**Comment by timsu92** [comment]
Nonetheless, I find it interesting that no matter which font I use, the line number in the upper-right cornor is always in the right position.
Maybe it would be nice to use variable regarding to that?

**Comment by junegunn** [comment]
Can you test this again with the latest version of fzf and see if anything's changed?

Excerpt from 0.36.0 changelog:

> - Better support for (Windows) terminals where each box-drawing character
>   takes 2 columns. Set `RUNEWIDTH_EASTASIAN` environment variable to `1`.

**Comment by timsu92** [comment]
Unfortunately, no😭 Neither the original nor the length of horizontal lines.
I'm on `fzf` V0.38.0 and [most recent fzf-git](https://github.com/junegunn/fzf-git.sh/commit/f36662f) and NerdFont V2.3.3 (JetBrains Mono Regular Nerd Font Complete Windows Compatible)

Althought I didn't see any difference between leaving `RUNEWIDTH_EASTASIAN` unset and setting it `1`, searching this I see other people talk about system language settings, and I see difference!
I set my Ubuntu to `zh_TW.UTF-8`, and both above problems and yet other problems (the border isn't bonding the preview window and there are dashes) shows:
![image](https://user-images.githubusercontent.com/33785401/220231497-cc2d491b-b7e5-4616-9628-2ba60194d2e5.png)
However, if I switch to `en_US.UTF-8`, problems are gone! There's only a line I'm not understanding it's meaning.
![image](https://user-images.githubusercontent.com/33785401/220233252-e790209c-8c69-4baf-a210-cccf48f91399.png)

But I really love to use my system in Chinese...

**Comment by timsu92** [comment]
Excerpt from 0.36.0 changelog:
> On Vim, the variable will be automatically set if &ambiwidth is double

But this var in my Vim is `single`, and changing it to `double` will break status line, which is rendered by powerline. This change allows fzf window to show in a currect size, but the horizontal lines will be in dashes.

**Comment by junegunn** [comment]
This issue is pretty old. Do you still have the problem with the latest version of fzf?

**Comment by timsu92** [comment]
Sorry I temporarily can't setup fzf with bat. I'll try again later
