### ISSUE TITLE
[feature request] fish support

### ISSUE THREAD

**Issue by tigerinus** [junegunn/fzf-git.sh#22]
Would be awesome to support fish. Thanks!

**Comment by junegunn** [comment]
Thanks for the suggestion, but I'm not a fish user and I'm not well-versed in its non-standard scripting facility. So, no, I'm not interested in supporting it.

**Comment by j-lakeman** [comment]
Would you accept a PR if someone ported it to fish?

**Comment by j-lakeman** [comment]
AFAIK fish has far better readability than Shell or Bash, similar to Python. Only it lacks few "advanced" features Bash has got e.g. dictionaries. In its documentation there is even a dedicated section [fish for Bash users](https://fishshell.com/docs/current/fish_for_bash_users.html#).
I could imagine porting your code to fish.

**Comment by junegunn** [comment]
> I could imagine porting your code to fish.

Are you interested in doing that?

**Comment by j-lakeman** [comment]
I'd give it a try at least. Can't promise anything though!
