### ISSUE TITLE
Keybings macOS

### ISSUE THREAD

**Issue by CpnNixel** [junegunn/fzf-git.sh#24]
It appears no keybinds work in my macOS Ventura 13.3, or maybe I'm doing something wrong.

Is it supposed to work on macOS or separate PR is needed?

**Comment by RyanzpLee** [comment]
I'm also having the same issue

**Comment by RyanzpLee** [comment]
Looks like the issue for me was having `export KEYTIMEOUT=1` in my `.zshrc`. Once I commented it out, the keybindings were working again

**Comment by 1Mark** [comment]
> Looks like the issue for me was having `export KEYTIMEOUT=1` in my `.zshrc`. Once I commented it out, the keybindings were working again

Can confirm 
```
unset KEYTIMEOUT
source fzf-git.sh
```
fixed it for me using oh-my-zsh on macOS Ventura (13.3)

**Comment by breskeby** [comment]
I still see that issue even with `unset KEYTIMEOUT`

**Comment by breskeby** [comment]
never mind. issues disappeared once I was within a git repo 🤦
