### ISSUE TITLE
Ctrl-g Ctrl-b keybinding does not work if tmux prefix is Ctrl-b

### ISSUE THREAD

**Issue by phelipetls** [junegunn/fzf-git.sh#3]
This happens either in zsh and bash, not sure how to work around it other than using a different keybinding.

**Comment by junegunn** [comment]
Good point, let me see what I can do.

**Comment by junegunn** [comment]
I've tried something like this only to find out the default bindkey always takes precedence over `C-b` in `fzf-git` key table.

```sh
set-option -g prefix c-b

bind -T fzf-git C-b send-keys C-g C-b
bind -n C-g switch-client -T fzf-git
```

Not sure what we should do. An easy solution would be to also bind these stuff to `<ALT-G> <ALT-*>`, or `<CTRL-
G> *`.
