### ISSUE TITLE
Incompatibility with XQuartz

### ISSUE THREAD

**Issue by electriquo** [junegunn/fzf-git.sh#33]
Thank you for fzf and for this Git key binding, **your work is amazing**.

Following the instructions, after sourcing fzf-git.sh https://github.com/junegunn/fzf-git.sh/blob/aacab4ae557657e0f9de288d688f312a28b86d21/README.md?plain=1#L20 it stopped macOs [XQuartz application](https://github.com/XQuartz/XQuartz/) from loading.

Reading through https://github.com/XQuartz/XQuartz/issues/325, I did not find `shift` in fzf-git.sh but couldn't track what causes it to make XQuartz fail to start.

**Comment by junegunn** [comment]
Thanks for the report. I've had the problem of XQuartz not starting recently, never thought this was related. Very strange! I'll look into it.

**Comment by junegunn** [comment]
Please test if bc0d5d2 fixes the problem for you.
