### ISSUE TITLE
Key-bindings for bash do not work in vi mode

### ISSUE THREAD

**Issue by ishaan-kapoor** [junegunn/fzf-git.sh#39]
on pressing the key bind the function name is entered in the prompt and the shell goes from insert mode to normal mode.
e.g.  `_fzf_git_branches` is put when I press Ctrl+G + Ctrl+B in insert mode.
and nothing happens when trying keybinds in normal mode (which is expected i guess)

**Comment by Jobin-Nelson** [comment]
Adding this line fixed this issue for me
![image](https://github.com/junegunn/fzf-git.sh/assets/86906246/3a1bb008-9b88-4788-a9e9-febbbcc40406)

**Comment by ishaan-kapoor** [comment]
this means that I will have to press `Alt+Ctrl+E` or `Esc` followed by `Ctrl+E` after `Ctrl+G Ctrl+B`, right?
I can achieve the same result by pressing enter as `\`_fzf_git_branches\`` is already in the line.
