### ISSUE TITLE
Ctrl-g Ctrl-s keybinding does not work if flow control is active

### ISSUE THREAD

**Issue by phelipetls** [junegunn/fzf-git.sh#4]
This is expected, but since that is the default keybinding to open `_fzf_git_stashes`, it'll likely cause a bad user experience since the screen freeze if flow control is active, until the user hits <kbd>Ctrl-q</kbd>.

Maybe consider a different keybinding or tell people to disable flow control in the README?

**Comment by junegunn** [comment]
Thanks. I hadn't thought of that.

> Maybe consider a different keybinding or tell people to disable flow control in the README?

Good idea.
