### ISSUE TITLE
Add colorless mode

### ISSUE THREAD

**Issue by sobolevn** [junegunn/fzf-git.sh#44]
Hi! Great stuff.

Some people are not that great with colors. Can a mode without `git` colors be added please?
I am specifically talking about things like:
- https://github.com/junegunn/fzf-git.sh/blob/23a74efafac72b0a131a9f897a5da2fc9bbc04ee/fzf-git.sh#L28
- https://github.com/junegunn/fzf-git.sh/blob/23a74efafac72b0a131a9f897a5da2fc9bbc04ee/fzf-git.sh#L31
- https://github.com/junegunn/fzf-git.sh/blob/23a74efafac72b0a131a9f897a5da2fc9bbc04ee/fzf-git.sh#L37

I would propose to add a setting called `FZF_GIT_NO_COLOR=true` to disable these colors :)
Would you accept a PR like this?

**Comment by junegunn** [comment]
Have you considered adding `--no-color` to your `$FZF_DEFAULT_OPTS`? It will suppress all colors from fzf.

**Comment by sobolevn** [comment]
Some colors are fine. But, the ones I've linked are too much :)

**Comment by junegunn** [comment]
Okay then, what do you think about changing `--color=always` to `--color=${FZF_GIT_COLOR:-always}`? So you can `export FZF_GIT_COLOR=auto`.

**Comment by sobolevn** [comment]
Looks good to me! 👍

**Comment by junegunn** [comment]
I've given it some thought and I think we should follow https://no-color.org/.

**Comment by junegunn** [comment]
Or maybe not? If fzf starts respecting `$NO_COLOR`, you'll lose all colors.

**Comment by sobolevn** [comment]
I think that supporting `NO_COLOR` is always a good thing. But, this is a global switch. I think that adding `FZF_GIT_COLOR` is also a good idea. This way:
- `NO_COLOR` has the main priority
- `FZF_GIT_COLOR` has the second priority
- By default all colors are shown

**Comment by junegunn** [comment]
How about this?

```diff
diff --git a/fzf-git.sh b/fzf-git.sh
index bef581d..27d01f0 100644
--- a/fzf-git.sh
+++ b/fzf-git.sh
@@ -27,11 +27,16 @@ __fzf_git_color() {
   if [[ -n $NO_COLOR ]]; then
     echo never
   else
-    echo always
+    echo ${FZF_GIT_COLOR:-always}
   fi
 }
 
 __fzf_git_cat() {
+  if [[ -n $FZF_GIT_CAT ]]; then
+    echo $FZF_GIT_CAT
+    return
+  fi
+
   # Sometimes bat is installed as batcat
   _fzf_git_bat_options="--style='${BAT_STYLE:-full}' --color=$(__fzf_git_color) --pager=never"
   if command -v batcat > /dev/null; then
```

**Comment by sobolevn** [comment]
amazing! 🚀

**Comment by junegunn** [comment]
That would allow something like this:

```sh
export FZF_GIT_COLOR=never
export FZF_GIT_CAT='bat --style=numbers --color=always'
```

But the problem with this is that, the preview window of CTRL-G-F has colors because it's using bat, but the preview windows of the other bindings, such as CTRL-G-H, do not. 

So maybe we need another variable for controlling the colors in the preview window.

* FZF_GIT_COLOR
* FZF_GIT_PREVIEW_COLOR

**Comment by junegunn** [comment]
bd8ac4ba4c9d7d12b34f7fa2b0d334f50cdb5254

**Comment by sobolevn** [comment]
And with `export FZF_GIT_PREVIEW_COLOR=always` and `FZF_GIT_COLOR=never`:

<img width="788" alt="Снимок экрана 2024-05-14 в 16 05 54" src="https://github.com/junegunn/fzf-git.sh/assets/4660275/41afdba3-ed97-4c6d-8161-11b7c2262a2b">

🎉
